version: "3"
services:
  db_drivenops:
    image: postgres:13
    container_name: db_drivenops
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env.docker
    networks:
      - drivenops_network
    volumes:
      - postgres:/var/lib/postgresql/data
  
  node_app_drivenops:
    container_name: node_app_drivenops
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_drivenops
    env_file:
      - ./back-end/.env.docker
    networks:
      - drivenops_network

  react_app_drivenops:
    build: ./front-end
    container_name: react_app_drivenops
    volumes:
      - build_react:/var/www/html
    env_file:
      - ./front-end/.env
    networks:
      - drivenops_network
    depends_on:
      - db_drivenops
      - node_app_drivenops
  
  nginx_drivenops:
    build: ./nginx
    container_name: nginx_drivenops
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    networks:
      - drivenops_network
    depends_on:
      - db_drivenops
      - node_app_drivenops
      - react_app_drivenops

networks:
  drivenops_network:
    driver: bridge

volumes:
  postgres:
  build_react:


# docker-compose -f somefile.yml up (...)