services:
  db_drivenops:
    image: postgres:13
    container_name: db_drivenops
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.docker
    networks:
      - drivenops_network
    volumes:
      - postgres:/var/lig/postgresql/data
  
  node_app:
    container_name: node_app
    build: .
    ports:
      - 4000:5000
    depends_on:
      - db_drivenops
    env_file:
      - .env.docker
    networks:
      - drivenops_network

networks:
  drivenops_network:
    driver: bridge

volumes:
  postgres: